resources:
  - name: helm_hub_sync_pr
    type: GitRepo
    configuration:
      gitProvider: jfrogsolutionsci_github
      path: jfrog/helm-hub-sync
      files:
        exclude: .pipelines/.*.yml$
      branches:
        exclude: master
      buildOn:
        commit: false
        pullRequestCreate: true

pipelines:
  - name: helmHubSyncPr
    steps:
      - name: build_image_pr
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: helm-hub-sync
          dockerImageTag: $run_number
          inputResources:
            - name: helm_hub_sync_pr
          integrations:
            - name: cpe_pipeline_slack
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting helmHubSyncPr ${step_name}_buildNumber=${run_number}" 
          onSuccess:
            - send_notification cpe_pipeline_slack --text "helmHubSyncPr ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "helmHubSyncPr ${step_name}_buildNumber=${run_number} - FAILED"
