resources:
  - name: helm_hub_sync_release
    type: GitRepo
    configuration:
      gitProvider: jfrogsolutionsci_github
      path: jfrog/helm-hub-sync
      files:
        exclude: .pipelines/.*.yml$
      branches:
        include: master
      tags:
        include: .*.*.*
      buildOn:
        commit: false
        tagCreate: true

pipelines:
  - name: helmHubSyncRelease
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: bldGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: helm-hub-sync
          dockerImageTag: $res_helm_hub_sync_release_gitTagName
          inputResources:
            - name: helm_hub_sync_release
          integrations:
            - name: cpe_pipeline_slack
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting helmHubSyncPr ${step_name}_buildNumber=${run_number}" 
          onSuccess:
            - send_notification cpe_pipeline_slack --text "helmHubSyncPr ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "helmHubSyncPr ${step_name}_buildNumber=${run_number} - FAILED"
      - name: push_image
        type: Bash
        configuration:
          affinityGroup: bldGroup
          environmentVariables:
            TAG_NAME: $res_helm_hub_sync_release_gitTagName
            BINTRAY_REPO: ${int_jfrogsolutionsci_bintray_repo//_/-}.bintray.io
          inputResources:
            - name: helm_hub_sync_release
              trigger: false
          integrations:
            - name: jfrogsolutionsci_bintray
            - name: cpe_pipeline_slack
          inputSteps:
            - name: build_image
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting helmHubSyncRelease of docker image ${step_name}_buildNumber=${run_number}" 
          onExecute:
            - docker login -u=${int_jfrogsolutionsci_bintray_user} -p=${int_jfrogsolutionsci_bintray_password} ${BINTRAY_REPO}
            - docker tag helm-hub-sync:${TAG_NAME} ${BINTRAY_REPO}/helm-hub-sync:${TAG_NAME}
            - docker push ${BINTRAY_REPO}/helm-hub-sync:${TAG_NAME}
          onSuccess:
            - send_notification cpe_pipeline_slack --text "helmHubSyncRelease ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "helmHubSyncRelease ${step_name}_buildNumber=${run_number} - FAILED"
